import React, { Component } from "react";
import { Link } from "react-router-dom";
import "./boards.css";
import BrandStatement from "../../components/BrandStatement/brandStatement";
import "../../components/BrandStatement/brandStatement.css";
import Logo from "../../components/Logo/logo";
import "../../components/Logo/logo.css";

class Boards extends Component {
  render() {
    return (
      <React.Fragment>
        <Logo />
        <div className="main-container">
          <h1>Boards</h1>
          <div className="container">
            <h2>Havasu Falls Trip - board name created by User</h2>
            <h4>
              Location name by region or country - generated by Google Maps
            </h4>
            <p>
              Location should be a href link that takes users to a map that
              generates a time efficient road map/directions to each stop pulled
              from the pictures' locations tagged by user.
            </p>
            <p>Need to add clickable/scrollable modal to images.</p>
            <div class="row">
              <div class="col">
                <img
                  className="enlarge"
                  src="./../../images/havasu.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu1.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu2.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu3.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu4.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu5.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu6.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu7.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu8.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu9.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu10.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/havasu11.jpg"
                  height="200px"
                  width="200px"
                />
              </div>
            </div>
          </div>

          <div className="container">
            <h2>Olympic National Park Trip - board name created by User</h2>
            <h4>
              Location name by region or country - generated by Google Maps
            </h4>
            <p>
              Location should be a href link that takes users to a map that
              generates a time efficient road map/directions to each stop pulled
              from the pictures' locations tagged by user.
            </p>
            <p>Need to add clickable/scrollable modal to images.</p>
            <div class="row">
              <div class="col">
                <img
                  className="enlarge"
                  className="enlarge"
                  src="./../../images/olympic.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic1.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic2.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic3.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic4.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic5.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic6.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic7.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic8.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic9.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic10.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic11.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/olympic12.jpg"
                  height="200px"
                  width="200px"
                />
              </div>
            </div>
          </div>

          <div className="container">
            <h2>Seattle Trip - board name created by User</h2>
            <h4>
              Location name by region or country - generated by Google Maps
            </h4>
            <p>
              Location should be a href link that takes users to a map that
              generates a time efficient road map/directions to each stop pulled
              from the pictures' locations tagged by user.
            </p>
            <p>Need to add clickable/scrollable modal to images.</p>
            <div class="row">
              <div class="col">
                <img
                  className="enlarge"
                  className="enlarge"
                  src="./../../images/seattle.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle1.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle2.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle3.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle4.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle5.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle6.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle7.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle8.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle9.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle10.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle11.jpg"
                  height="200px"
                  width="200px"
                />

                <img
                  className="enlarge"
                  src="./../../images/seattle12.jpg"
                  height="200px"
                  width="200px"
                />
              </div>
            </div>
          </div>
        </div>
      </React.Fragment>
    );
  }
}

export default Boards;
