
/*
AUTH ACTIONS
*/
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


/*
PHOTO ACTIONS
*/
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const DELETE_PHOTO = 'DELETE_PHOTO';

/*
USER ACTIONS
*/

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
